@extends('layout.dashboard')

@section('title', 'Orders | Sweat Nothing')

@section('content')
    <main class="mx-auto max-w-[1500px] p-5 lg:p-7">
        <section class="flex flex-col justify-between gap-4 md:flex-row md:items-end">
            <div>
                <h1 class="text-2xl font-bold tracking-[-.03em]">Orders</h1>
                <p class="mt-1 text-slate-500">Manage and track all orders from your store.</p>
            </div>

            <nav class="flex items-center gap-2 text-sm text-slate-500" aria-label="Breadcrumb">
                <a href="{{ route('dashboard') }}" class="hover:text-black">Dashboard</a>
                <span>&#8250;</span>
                <span>Orders</span>
            </nav>
        </section>
        {{-- Page heading section ends here. --}}

        <section class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <article class="rounded-xl bg-white p-5 shadow-sm"><div class="flex items-center gap-4"><span class="grid h-14 w-14 place-items-center rounded-full bg-[#fff3cf] text-2xl">&#128722;</span><div><p class="text-xs text-slate-500">Total Orders</p><p class="mt-1 text-2xl font-bold">142</p><p class="mt-1 text-xs text-emerald-600">&#8593; +18% <span class="text-slate-500">this month</span></p></div></div></article>
            <article class="rounded-xl bg-white p-5 shadow-sm"><div class="flex items-center gap-4"><span class="grid h-14 w-14 place-items-center rounded-full bg-[#dff7e6] text-2xl">&#9632;</span><div><p class="text-xs text-slate-500">Delivered</p><p class="mt-1 text-2xl font-bold">86</p><p class="mt-1 text-xs text-emerald-600">&#8593; +22% <span class="text-slate-500">this month</span></p></div></div></article>
            <article class="rounded-xl bg-white p-5 shadow-sm"><div class="flex items-center gap-4"><span class="grid h-14 w-14 place-items-center rounded-full bg-[#e2efff] text-2xl">&#128666;</span><div><p class="text-xs text-slate-500">Processing</p><p class="mt-1 text-2xl font-bold">34</p><p class="mt-1 text-xs text-emerald-600">&#8593; +8% <span class="text-slate-500">this month</span></p></div></div></article>
            <article class="rounded-xl bg-white p-5 shadow-sm"><div class="flex items-center gap-4"><span class="grid h-14 w-14 place-items-center rounded-full bg-[#ffe3e3] text-2xl">&#10005;</span><div><p class="text-xs text-slate-500">Cancelled</p><p class="mt-1 text-2xl font-bold">22</p><p class="mt-1 text-xs text-emerald-600">&#8593; +5% <span class="text-slate-500">this month</span></p></div></div></article>
        </section>
        {{-- Order statistic cards section ends here. --}}

        <section class="mt-5 rounded-xl bg-white p-4 shadow-sm lg:p-5">
            <div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
                <div class="grid gap-3 sm:grid-cols-3">
                    <select class="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none"><option>All Status</option><option>Delivered</option><option>Processing</option><option>Shipped</option><option>Cancelled</option></select>
                    <input class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none" type="date" aria-label="Select order date">
                    <label class="flex items-center gap-2 rounded-lg bg-[#f5f7f9] px-3 py-2.5 text-sm text-slate-500"><span>&#9906;</span><input class="w-full bg-transparent outline-none" type="search" placeholder="Search order ID, customer..."></label>
                </div>

                <button class="rounded-lg bg-[#111111] px-4 py-2.5 text-sm font-medium text-white transition hover:bg-black/80">+ Create Order</button>
            </div>
        </section>
        {{-- Order filter controls section ends here. --}}

        <section class="mt-4 overflow-hidden rounded-xl bg-white shadow-sm">
            <div class="overflow-x-auto">
                <table class="min-w-[1180px] w-full text-left text-sm">
                    <thead class="bg-[#f5f7f9] text-xs font-semibold text-slate-800"><tr><th class="px-4 py-3"><input type="checkbox" aria-label="Select all orders"></th><th class="px-4 py-3">#</th><th class="px-4 py-3">Order ID</th><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Products</th><th class="px-4 py-3">Total Amount</th><th class="px-4 py-3">Payment</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Action</th></tr></thead>
                    <tbody class="divide-y divide-slate-100 text-slate-700">
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN1001"></td><td class="px-4 py-3">1</td><td class="px-4 py-3 font-medium">#SN1001</td><td class="px-4 py-3"><p>Aarav Sharma</p><p class="text-xs text-slate-500">aarav@gmail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#efe2c7] text-[8px] font-bold">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+2</span></div></td><td class="px-4 py-3 font-semibold">₹ 2,450</td><td class="px-4 py-3">Online (UPI)</td><td class="px-4 py-3"><span class="rounded-md bg-emerald-100 px-3 py-2 text-xs font-medium text-emerald-700">Delivered</span></td><td class="px-4 py-3 text-xs">21 Sep 2026<br><span class="text-slate-500">11:45 AM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN1000"></td><td class="px-4 py-3">2</td><td class="px-4 py-3 font-medium">#SN1000</td><td class="px-4 py-3"><p>Priya Mehta</p><p class="text-xs text-slate-500">priya@outlook.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+1</span></div></td><td class="px-4 py-3 font-semibold">₹ 1,890</td><td class="px-4 py-3">Online (Card)</td><td class="px-4 py-3"><span class="rounded-md bg-amber-100 px-3 py-2 text-xs font-medium text-amber-700">Processing</span></td><td class="px-4 py-3 text-xs">21 Sep 2026<br><span class="text-slate-500">10:20 AM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0999"></td><td class="px-4 py-3">3</td><td class="px-4 py-3 font-medium">#SN0999</td><td class="px-4 py-3"><p>Rahul Verma</p><p class="text-xs text-slate-500">rahulv@gmail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#efe2c7] text-[8px] font-bold">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+3</span></div></td><td class="px-4 py-3 font-semibold">₹ 3,120</td><td class="px-4 py-3">COD</td><td class="px-4 py-3"><span class="rounded-md bg-blue-100 px-3 py-2 text-xs font-medium text-blue-700">Shipped</span></td><td class="px-4 py-3 text-xs">20 Sep 2026<br><span class="text-slate-500">06:15 PM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0998"></td><td class="px-4 py-3">4</td><td class="px-4 py-3 font-medium">#SN0998</td><td class="px-4 py-3"><p>Sneha Kapoor</p><p class="text-xs text-slate-500">sneha.k@gmail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#efe2c7] text-[8px] font-bold">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+1</span></div></td><td class="px-4 py-3 font-semibold">₹ 650</td><td class="px-4 py-3">Online (UPI)</td><td class="px-4 py-3"><span class="rounded-md bg-emerald-100 px-3 py-2 text-xs font-medium text-emerald-700">Delivered</span></td><td class="px-4 py-3 text-xs">20 Sep 2026<br><span class="text-slate-500">02:40 PM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0997"></td><td class="px-4 py-3">5</td><td class="px-4 py-3 font-medium">#SN0997</td><td class="px-4 py-3"><p>Vikram Singh</p><p class="text-xs text-slate-500">vikram.singh@gmail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#ad733f] text-[8px] font-bold text-white">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+2</span></div></td><td class="px-4 py-3 font-semibold">₹ 2,100</td><td class="px-4 py-3">Online (Card)</td><td class="px-4 py-3"><span class="rounded-md bg-red-100 px-3 py-2 text-xs font-medium text-red-700">Cancelled</span></td><td class="px-4 py-3 text-xs">19 Sep 2026<br><span class="text-slate-500">01:12 PM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0996"></td><td class="px-4 py-3">6</td><td class="px-4 py-3 font-medium">#SN0996</td><td class="px-4 py-3"><p>Neha Jain</p><p class="text-xs text-slate-500">neha.jain@ymail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#bd843c] text-[8px] font-bold text-white">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+1</span></div></td><td class="px-4 py-3 font-semibold">₹ 980</td><td class="px-4 py-3">COD</td><td class="px-4 py-3"><span class="rounded-md bg-amber-100 px-3 py-2 text-xs font-medium text-amber-700">Processing</span></td><td class="px-4 py-3 text-xs">18 Sep 2026<br><span class="text-slate-500">04:30 PM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0995"></td><td class="px-4 py-3">7</td><td class="px-4 py-3 font-medium">#SN0995</td><td class="px-4 py-3"><p>Karan Malhotra</p><p class="text-xs text-slate-500">karan.m@gmail.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#efe2c7] text-[8px] font-bold">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+4</span></div></td><td class="px-4 py-3 font-semibold">₹ 4,320</td><td class="px-4 py-3">Online (NetBanking)</td><td class="px-4 py-3"><span class="rounded-md bg-emerald-100 px-3 py-2 text-xs font-medium text-emerald-700">Delivered</span></td><td class="px-4 py-3 text-xs">18 Sep 2026<br><span class="text-slate-500">11:05 AM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                        <tr><td class="px-4 py-3"><input type="checkbox" aria-label="Select order SN0994"></td><td class="px-4 py-3">8</td><td class="px-4 py-3 font-medium">#SN0994</td><td class="px-4 py-3"><p>Isha Gupta</p><p class="text-xs text-slate-500">isha.g@outlook.com</p></td><td class="px-4 py-3"><div class="flex items-center gap-1"><span class="grid h-9 w-8 place-items-center rounded bg-[#1f1f1f] text-[8px] font-bold text-[#ffd400]">SN</span><span class="grid h-9 w-8 place-items-center rounded bg-[#efe2c7] text-[8px] font-bold">SN</span><span class="rounded bg-slate-100 px-2 py-2 text-xs">+1</span></div></td><td class="px-4 py-3 font-semibold">₹ 1,250</td><td class="px-4 py-3">Online (UPI)</td><td class="px-4 py-3"><span class="rounded-md bg-blue-100 px-3 py-2 text-xs font-medium text-blue-700">Shipped</span></td><td class="px-4 py-3 text-xs">17 Sep 2026<br><span class="text-slate-500">03:22 PM</span></td><td class="px-4 py-3"><button class="rounded-lg bg-slate-50 px-3 py-2">&#128065;</button></td></tr>
                    </tbody>
                </table>
            </div>

            <div class="flex flex-col gap-3 border-t border-slate-100 px-4 py-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>Showing 1 to 8 of 142 orders</p><div class="flex items-center gap-2"><button class="rounded-lg bg-slate-100 px-3 py-2">&#8249;</button><button class="rounded-lg bg-[#ffd400] px-3 py-2 font-medium text-black">1</button><button class="rounded-lg px-3 py-2">2</button><button class="rounded-lg px-3 py-2">3</button><button class="rounded-lg px-3 py-2">4</button><button class="rounded-lg bg-slate-100 px-3 py-2">&#8250;</button></div></div>
        </section>
        {{-- Orders table and pagination section ends here. --}}
    </main>
@endsection
